# -*- coding: utf-8 -*-
"""Agent Gateway (FastAPI) entrypoint.

This module exposes the FastAPI `app`, portal shell helper, and route handlers.
"""
from agent_memory_lib import MemoryClient
from agent_runtime.product.cli import _load_agent_class
from agent_runtime.product.gateway.app import app, create_app
from agent_runtime.product.gateway.core_routes import (
    chat,
    chat_stream,
    full_chain_dependencies,
    full_chain_logs,
    full_chain_logs_stream,
    full_chain_restart,
    full_chain_services,
    full_chain_start,
    full_chain_status,
    full_chain_stop,
    get_run_trace,
    health,
    healthz,
    list_agents,
    list_runs,
    memory_get,
    memory_read,
    memory_search,
    memory_write,
    readyz,
)
from agent_runtime.product.gateway.portal_helpers import (
    _auth_store,
    _bearer_token_from_headers,
    _build_mcp_clients_from_workspace_config,
    _embedding_service_health,
    _get_conversation_store,
    _load_portal_config,
    _memory_service_health,
    _neo4j_health,
    _PORTAL_CONFIG_PATH,
    _obs_store,
    _usage_store,
    _redis_health,
    _request_id_from_headers,
    _require_workspace_id,
    _tool_policy_for_workspace,
    _trace_id_from_headers,
    _workspace_mcp_clients,
)
from agent_runtime.product.gateway.portal_routes import (
    portal_add_workspace_member,
    portal_apply_workspace_config,
    portal_audit,
    portal_audit_export,
    portal_change_password,
    portal_delete_agent,
    portal_delete_workspace,
    portal_delete_workspace_member,
    portal_get_tool_policy,
    portal_get_workspace,
    portal_get_workspace_config,
    portal_list_admin_users,
    portal_admin_usage,
    portal_list_admin_quotas,
    portal_list_agents,
    portal_list_tools,
    portal_list_workspace_members,
    portal_list_workspaces,
    portal_login,
    portal_logout,
    portal_me,
    portal_memory_index_rebuild,
    portal_memory_read,
    portal_memory_stats,
    portal_metrics,
    portal_metrics_export,
    portal_refresh,
    portal_set_tool_policy,
    portal_set_admin_quota,
    portal_set_workspace_config,
    portal_signup,
    portal_tools_status,
    portal_upsert_agent,
)
from agent_runtime.product.gateway.portal_shell import _portal_shell_html
from agent_runtime.product.gateway.models import (
    PortalAgentUpsertRequest,
    PortalMeResponse,
    AdminQuotaRequest,
    ToolPolicyRequest,
    WorkspaceConfigRequest,
    WorkspaceMemberRequest,
    FileFirstGetProxyRequest,
    FileFirstReadProxyRequest,
    FileFirstSearchProxyRequest,
    FileFirstWriteProxyRequest,
)
from agent_runtime.product.chat_models import ChatMessage, ChatRequest, ChatResponse
from agent_memory_framework.llm_clients import create_azure_openai_client

__all__ = [
    "app",
    "create_app",
    "_portal_shell_html",
    "MemoryClient",
    "create_azure_openai_client",
    "_load_agent_class",
    # Helpers/state
    "_auth_store",
    "_PORTAL_CONFIG_PATH",
    "_bearer_token_from_headers",
    "_get_conversation_store",
    "_load_portal_config",
    "_build_mcp_clients_from_workspace_config",
    "_workspace_mcp_clients",
    "_tool_policy_for_workspace",
    "_request_id_from_headers",
    "_trace_id_from_headers",
    "_require_workspace_id",
    "_redis_health",
    "_neo4j_health",
    "_embedding_service_health",
    "_memory_service_health",
    "_obs_store",
    "_usage_store",
    # Core routes
    "health",
    "healthz",
    "readyz",
    "list_agents",
    "full_chain_dependencies",
    "full_chain_status",
    "full_chain_services",
    "full_chain_stop",
    "full_chain_logs",
    "full_chain_logs_stream",
    "full_chain_start",
    "full_chain_restart",
    "memory_write",
    "memory_search",
    "memory_read",
    "memory_get",
    "chat",
    "chat_stream",
    "list_runs",
    "get_run_trace",
    # Portal routes
    "portal_signup",
    "portal_login",
    "portal_refresh",
    "portal_logout",
    "portal_change_password",
    "portal_me",
    "portal_list_tools",
    "portal_list_agents",
    "portal_upsert_agent",
    "portal_delete_agent",
    "portal_tools_status",
    "portal_get_tool_policy",
    "portal_set_tool_policy",
    "portal_get_workspace_config",
    "portal_set_workspace_config",
    "portal_apply_workspace_config",
    "portal_memory_read",
    "portal_memory_stats",
    "portal_memory_index_rebuild",
    "portal_metrics",
    "portal_audit",
    "portal_metrics_export",
    "portal_audit_export",
    "portal_list_workspaces",
    "portal_get_workspace",
    "portal_delete_workspace",
    "portal_list_workspace_members",
    "portal_add_workspace_member",
    "portal_delete_workspace_member",
    "portal_list_admin_users",
    "portal_admin_usage",
    "portal_list_admin_quotas",
    "portal_set_admin_quota",
    # Models
    "ChatMessage",
    "ChatRequest",
    "ChatResponse",
    "PortalAgentUpsertRequest",
    "PortalMeResponse",
    "AdminQuotaRequest",
    "ToolPolicyRequest",
    "WorkspaceConfigRequest",
    "WorkspaceMemberRequest",
    "FileFirstGetProxyRequest",
    "FileFirstReadProxyRequest",
    "FileFirstSearchProxyRequest",
]
